import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import vm from 'node:vm';
const context = vm.createContext({ console });
for (const name of ['stages.js', 'campaign.js']) vm.runInContext(readFileSync(new URL(name, import.meta.url), 'utf8'), context);
const { Campaign, StageDefinition, AttackDefinition } = context.LongdanCore;
const fresh = (difficulty = 'normal') => { const g = new Campaign(difficulty); g.start(difficulty); g.chooseRoute('continue'); g.events = []; return g; };
const tick = (g, seconds, input = {}) => { for (let t = 0; t < seconds; t += .02) g.step(.02, input); };
const object = (g, id) => { const o = g.objects.find(o => o.id === id); assert(o, id); g.player.x = o.x; g.player.y = o.y; g.player.action = null; return o; };
const clear = (g, group = null) => { for (const e of [...g.enemies]) if (e.hp > 0 && (!group || e.group === group)) g.damageEnemy(e, 1e5, 0, 0, 'player', 0, true); };
const use = (g, id) => { object(g, id); return g.interact(); };
let g = fresh(); g.enemies = []; g.allies = []; g.rocks = []; g.huts = [];
const origin = { x: g.player.x, y: g.player.y }; tick(g, 1, { x: 1 }); assert(g.player.x > origin.x + 150); assert(g.player.walkDistance > 150);
g.mode = 'paused'; const x = g.player.x; tick(g, .5, { x: 1 }); assert.equal(g.player.x, x); g.mode = 'playing';
let e = g.spawnEnemy('spear', g.player.x + 95, g.player.y); e.cooldown = 99; g.player.dir = 0;
const hp = e.hp; assert(g.attack(0)); assert.equal(e.hp, hp, 'No damage before the actual weapon frames'); assert(!g.attack()); tick(g, .04); assert.equal(e.hp, hp); tick(g, .09); assert(e.hp < hp); const once = e.hp; tick(g, .1); assert.equal(e.hp, once, 'Active frames may not repeatedly damage the same enemy'); tick(g, .22);
g.attack(0); tick(g, .51); g.attack(0); assert.equal(g.player.combo, 3); tick(g, .8);
g = fresh(); g.enemies = []; g.allies = []; g.rocks = []; g.huts = []; g.player.invincible = 0; g.player.hp = 100;
assert(g.heal()); assert.equal(g.player.hp, 100, 'Medicine must have a use animation'); assert.equal(g.player.potions, 2); tick(g, .3); g.damageFriend(g.player, 10, 13); tick(g, 1); assert.equal(g.player.hp, 90, 'An interrupted medicine use may not heal later');
g.player.healCd = 0; assert(g.heal()); tick(g, 1.1); assert.equal(g.player.hp, 175);
g.player.invincible = 0; const qi = g.player.qi; g.dash(1, 0); g.damageFriend(g.player, 20, 800); assert.equal(g.precisionCount, 1); assert.equal(g.player.hp, 175); assert.equal(g.player.qi, qi - 16 + 12);
g.damageFriend(g.player, 20, 800); assert.equal(g.precisionCount, 1, 'One attack can credit only one precision dodge'); tick(g, .25); assert(g.attack(0)); assert.equal(g.player.action.key, 'counter'); tick(g, .5);
g.player.dashCd = 0; g.dash(1, 0); tick(g, .19); g.damageFriend(g.player, 10, 801); assert.equal(g.precisionCount, 1, 'Late invulnerability is not a precision dodge');
g = fresh(); g.enemies = []; g.allies = []; g.huts = []; g.rocks = []; g.player.invincible = 0;
e = g.spawnEnemy('sword', g.player.x + 70, g.player.y); e.action = g.newAction('enemy', { windup: .01, active: .13, recovery: .8, range: 145, arc: .7, damage: 25 }, Math.PI); e.attackDir = Math.PI;
g.dash(0, 1); tick(g, .02); assert.equal(g.precisionCount, 1, 'A real active weapon must trigger precision dodge on intersection'); tick(g, .12); assert.equal(g.precisionCount, 1);
g = fresh(); g.enemies = []; g.allies = []; g.huts = []; g.rocks = []; g.dash(1, 0); tick(g, .1); assert.equal(g.precisionCount, 0, 'An empty dodge must not produce a counter reward');
g = fresh(); g.enemies = []; g.allies = []; g.huts = []; g.rocks = []; g.player.invincible = 999;
for (let i = 0; i < 5; i++) g.spawnEnemy('sword', g.player.x + 45 + i * 5, g.player.y + i * 4);
for (let i = 0; i < 150; i++) { g.step(.02); assert(g.enemies.filter(e => e.action && e.action.t < e.action.def.windup + e.action.def.active).length <= 2, 'At most two melee attacks may pressure the player simultaneously'); }
g = fresh(); g.enemies = []; g.allies = []; g.player.invincible = 0;
e = g.spawnEnemy('shield', g.player.x + 65, g.player.y); e.dir = Math.PI; const shieldHp = e.hp;
g.damageEnemy(e, 40, 0, 0, 'player', 10); assert.equal(e.hp, shieldHp - 9.6); g.damageEnemy(e, 40, 0, 0, 'player', 10, true); assert(e.shieldBroken > 0); assert.equal(e.hp, shieldHp - 49.6);
g = fresh(); g.enterStage('bridge'); g.flags.adou = true; g.flags.house = true; g.flags.committed = true;
assert.equal(g.allies.length, 3); e = g.enemies[0]; for (let i = 0; i < 300; i++) g.damageEnemy(e, 3.5, 0, 0, 'ally', 0, true); assert.equal(e.hp, e.maxHp * .22, 'The squad must not win fights without player participation'); assert.equal(g.kills, 0); assert.equal(g.player.rage, 0);
g = fresh(); assert(!use(g, 'toVillage')); clear(g); assert(g.flags.mountain); use(g, 'campMountain'); assert.equal(g.checkpoint.stage, 'mountain'); assert(use(g, 'toVillage')); assert.equal(g.stage, 'village');
assert(!use(g, 'civilians')); clear(g, 'vRescue'); assert(use(g, 'civilians')); g.chooseRoute('continue'); assert(g.flags.healer && g.flags.civilians); const historyCount = g.history.length; assert(!use(g, 'civilians')); assert.equal(g.history.length, historyCount);
clear(g); use(g, 'toTemple'); assert.equal(g.stage, 'temple'); clear(g); use(g, 'xiahouGate'); assert.equal(g.mode, 'dialog'); g.chooseRoute('bossStart:xiahou'); assert.equal(g.activeBoss, 'xiahou'); assert.equal(g.enemies.filter(e => e.hp > 0).length, 1);
const firstBossHealth = g.boss.maxHp; g.player.hp = 0; g.mode = 'playing'; g.defeat('test', 'test'); assert(g.retry()); assert.equal(g.boss.hp, firstBossHealth); assert(g.flags.civilians); assert.equal(g.player.potions, 3); assert.equal(g.mode, 'playing');
clear(g); assert(g.flags.temple && g.flags.sword); assert.equal(g.mode, 'dialog'); g.chooseRoute('continue');
g.player.rage = 100; assert(g.ultimate()); assert.equal(g.player.rage, 0); tick(g, 1);
use(g, 'shortcut'); assert.equal(g.stage, 'village'); assert(g.flags.healer); assert.equal(g.enemies.filter(e => e.group === 'vRescue').length, 0); use(g, 'toTemple'); use(g, 'toHouse'); assert.equal(g.stage, 'house');
clear(g); use(g, 'adou'); assert(g.flags.adou); g.chooseRoute('rescue'); assert(g.rescue); assert(g.squadActive());
clear(g, 'rescue1'); tick(g, 1.6); assert.equal(g.rescue.wave, 2); g.rescue.healer.hp = 0; tick(g, .02); assert.equal(g.mode, 'defeat'); g.retry(); assert.equal(g.rescue.wave, 1); assert(g.flags.adou && g.flags.healer); assert(!g.flags.mother);
clear(g, 'rescue1'); tick(g, 1.6); clear(g, 'rescue2'); tick(g, 20); assert(g.flags.mother && g.flags.house); g.chooseRoute('continue');
use(g, 'toFork'); clear(g); use(g, 'supplies'); assert.equal(g.boss.type, 'elite'); g.damageEnemy(g.boss, 1e5, 0, 0, 'player', 0, true); use(g, 'supplies'); assert(g.flags.supplies && g.flags.elite);
use(g, 'toBridge'); assert.equal(g.mode, 'dialog'); g.chooseRoute('continue'); assert.equal(g.stage, 'fork'); assert(!g.flags.committed); use(g, 'toBridge'); g.chooseRoute('commit'); assert.equal(g.stage, 'bridge'); assert(g.flags.committed);
assert.equal(g.enemies.filter(e => e.type === 'archer').length, 0, 'Burning supplies must remove the real bridge archer formation'); assert(!g.blocking(1100, 900)); assert.equal(g.civilians.length, 4);
clear(g); use(g, 'zhangheGate'); g.chooseRoute('bossStart:zhanghe'); assert.equal(g.activeBoss, 'zhanghe'); assert(!g.squadActive()); const zhanghe = g.boss;
g.damageEnemy(zhanghe, zhanghe.maxHp * .51); tick(g, .02); assert(zhanghe.phase2); assert(zhanghe.phaseTime > 0); tick(g, 1.4);
const patterns = new Set(); for (let i = 0; i < 8; i++) { zhanghe.sequence = []; g.startEnemyAction(zhanghe, g.player); patterns.add(zhanghe.action.def.name); zhanghe.action = null; }
assert([...patterns].some(name => name.includes('回身'))); assert([...patterns].some(name => name.includes('迟势')));
clear(g); g.chooseRoute('continue'); use(g, 'exit'); assert.equal(g.mode, 'ending'); assert.equal(g.result.people, 3); assert(g.result.mother && g.result.supplies); assert.match(g.result.title, /母子同归/);
// A main-only run and a return-for-healer run must both remain playable.
g = fresh(); clear(g); use(g, 'toVillage'); clear(g); use(g, 'toTemple'); clear(g); use(g, 'xiahouGate'); g.chooseRoute('bossStart:xiahou'); clear(g); g.chooseRoute('continue'); use(g, 'toHouse'); clear(g); use(g, 'adou'); g.chooseRoute('findHealer'); assert.equal(g.getMission().target.id, 'backTemple');
use(g, 'backTemple'); assert.equal(g.getMission().target.id, 'shortcut'); use(g, 'shortcut'); assert.equal(g.getMission().target.id, 'civilians'); use(g, 'civilians'); g.chooseRoute('continue'); assert(g.flags.healer); use(g, 'toTemple'); use(g, 'toHouse'); use(g, 'adou'); g.chooseRoute('leaveMother'); use(g, 'toFork'); clear(g, 'f1'); use(g, 'toBridge'); g.chooseRoute('commit'); assert.equal(g.enemies.filter(e => e.type === 'archer').length, 2); assert(g.blocking(1100, 900)); clear(g); use(g, 'zhangheGate'); g.chooseRoute('bossStart:zhanghe'); clear(g); g.chooseRoute('continue'); use(g, 'exit'); assert(g.result.won && !g.result.mother && !g.result.supplies);
// Snapshots preserve progress, replay only the interrupted encounter, and reject bad data.
g = fresh(); clear(g); use(g, 'toVillage'); clear(g); const saved = JSON.parse(JSON.stringify(g.snapshot())); assert(Campaign.validSnapshot(saved)); const restored = new Campaign(); assert(restored.restore(saved)); assert.equal(restored.stage, 'village'); assert.equal(restored.enemies.length, 0); assert.equal(restored.kills, g.kills);
assert(!restored.restore({ ...saved, version: 7 })); assert(!restored.restore({ ...saved, checkpoint: { ...saved.checkpoint, x: 1e8 } }));
g = fresh(); g.enterStage('temple'); clear(g); use(g, 'xiahouGate'); g.chooseRoute('bossStart:xiahou'); const bossSave = JSON.parse(JSON.stringify(g.snapshot())); assert(new Campaign().restore(bossSave)); const resumedBoss = new Campaign(); resumedBoss.restore(bossSave); assert.equal(resumedBoss.activeBoss, 'xiahou'); assert.equal(resumedBoss.enemies.filter(e => e.hp > 0).length, 1);
g = fresh(); g.enterStage('village'); g.rocks = []; g.huts = [{ x: 800, y: 550, w: 180, h: 150 }]; const escort = { x: 580, y: 550, r: 12, moving: false }; const path = g.findPath(escort.x, escort.y, 1040, 550, 12); assert(path.length); assert(path.every(p => !g.blocking(p.x, p.y, 12)));
for (let i = 0; i < 700; i++) { g.time += .02; g.navigate(escort, 1040, 550, 180, .02); } assert(Math.hypot(escort.x - 1040, escort.y - 550) < 50, 'Escorts must go around hut corners');
g = fresh(); g.enterStage('bridge'); const walker = { x: 930, y: 420, r: 12 }; const bridgePath = g.findPath(walker.x, walker.y, 1270, 130, 12); assert(bridgePath.length); assert(bridgePath.filter(p => p.y < 285).every(p => p.x > 1170 && p.x < 1370));
const html = readFileSync(new URL('./index.html', import.meta.url), 'utf8'); assert(!html.includes('GAME_SCRIPT')); assert(!html.includes('GAME_STYLES')); assert(!/<script[^>]+src=/.test(html));
const assetFiles = [...html.matchAll(/"assets\/([^"\n]+\.png)"/g)].map(match => match[1]); assert.equal(new Set(assetFiles).size, 6);
for (const asset of new Set(assetFiles)) assert(readFileSync(new URL('./assets/' + asset, import.meta.url)).length > 0);
assert(html.includes('id="touchControls"') && html.includes('id="joystick"') && html.includes('id="rotateScreen"'), 'The mobile build must include touch controls and rotation guidance');
assert(!/data-device|选择你的游玩方式|电脑版试玩/.test(html), 'This is a separate mobile edition, without a device chooser');
assert(html.includes('rel="manifest"') && html.includes('manifest.webmanifest'), 'The mobile page must advertise an installable landscape manifest');
assert(readFileSync(new URL('./manifest.webmanifest', import.meta.url), 'utf8').includes('"orientation": "landscape"'));
assert(readFileSync(new URL('./sw.js', import.meta.url), 'utf8').includes('CACHE_NAME'), 'The mobile page must cache its shell and character images');
const script = readFileSync(new URL('./game.js', import.meta.url), 'utf8'), shell = readFileSync(new URL('./shell.html', import.meta.url), 'utf8');
for (const [, id] of script.matchAll(/\$\('([^']+)'\)/g)) assert(shell.includes('id="' + id + '"'), 'Missing desktop UI element: ' + id);
assert(script.includes("'longdan.mobile.changban.v1'")); assert(!script.includes("'longdan.changban.v2'"), 'Mobile saves must not overwrite desktop saves on the same GitHub Pages origin');
vm.runInContext(readFileSync(new URL('./mobile-controls.js', import.meta.url), 'utf8'), context);
const { MobileInput, assistAim } = context.LongdanMobile;
const input = new MobileInput();
assert(input.beginStick(11, 150, 100, 100, 100, 50)); assert.equal(input.x, 1); assert.equal(input.y, 0);
assert(!input.beginStick(12, 20, 20, 100, 100, 50), 'A second finger cannot steal the movement stick');
assert(input.beginAction(12, 'attack')); assert(input.attack); assert.equal(input.x, 1);
assert(input.beginAction(13, 'dash')); input.release(13); assert(input.attack, 'Releasing a skill finger must not stop the attack finger'); assert.equal(input.x, 1);
input.release(11); assert.equal(input.x, 0); assert(input.attack, 'Releasing movement must not stop a separately held attack');
input.release(12); assert(!input.attack);
input.beginStick(21, 102, 102, 100, 100, 50); assert.equal(input.x, 0, 'Small joystick drift must remain in the dead zone');
assert(!input.moveStick(99, 300, 300)); input.moveStick(21, 300, 300); assert(Math.abs(Math.hypot(input.x, input.y) - 1) < .001, 'Diagonal movement must be normalized');
input.beginAction(22, 'attack'); input.clear(); assert(!input.attack && input.stickId === null && input.x === 0 && input.y === 0, 'Pause, rotation and pointer cancellation must clear held movement and attack');
assert.equal(assistAim({ x: 0, y: 0 }, [{ x: 20, y: 0, hp: 0 }, { x: 0, y: 80, hp: 50 }]), Math.PI / 2);
assert.equal(assistAim({ x: 0, y: 0 }, [{ x: 0, y: 500, hp: 50 }]), undefined, 'Touch aim must not lock onto distant enemies');
assert(script.includes('requestFullscreen') && script.includes("lock('landscape')"), 'A user gesture must attempt fullscreen landscape mode');
assert(script.includes('contextlost') && script.includes('contextrestored') && script.includes('visibilitychange'), 'The renderer must recover after a mobile surface interruption');
assert(script.includes('950000') && script.includes('1000 / 45'), 'The mobile renderer must cap backing pixels and render rate');
g = fresh(); g.mode = 'map'; const pausedTime = g.time; g.setCommand('hold'); assert.equal(g.command, 'hold'); tick(g, 1); assert.equal(g.time, pausedTime, 'Changing orders in the map must not run the battle');
assert.equal(Object.keys(StageDefinition).length, 6); assert(AttackDefinition.thrust3.recovery > AttackDefinition.thrust1.recovery);
console.log('PASS: combat, 6 regions, both story routes, 2 bosses, saved progression, escort navigation, all image assets, independent mobile saves, simultaneous joystick and attack, pointer release, normalized movement, cancellation, touch aim, map orders, landscape install metadata, offline image cache, surface recovery and mobile render budget.');
